clear all
close all 
clc

%% LCx determination
root_path         = 'D:/Paper3/Simulations/invivo/mi/cx/';
experiments_names = {'pig 4 HE','pig 4 MI', 'pig 5 HE','pig 5 MI', 'pig 6 HE','pig 6 MI', 'pig 7 HE','pig 7 MI'};
result_names      = {'sample4/results_he_CL1000_3000ms', ...
                    'sample4/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE', ...
                    'sample5/results_he_CL1000_3000ms', ...
                    'sample5/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE', ...
                    'sample6_x/results_he_CL1000_3000ms', ...
                    'sample6_x/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE', ...
                    'sample7/results_he_CL1000_3000ms', ...
                    'sample7/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE'};
dt_sim            = 0.00025; %s
pecg_name         = {'pECG_electrodesoriginal_norot',...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot'};
results_folder_name = 'ecg_results_electrodesoriginal_norot_miECG_LCx';

colorHE = [0 0.4470 0.7410];
colorMI = [0.8500 0.3250 0.0980];

colors = {colorHE, colorMI, colorHE, colorMI, colorHE, colorMI, colorHE, colorMI};

lines = ["-","-","--","--",":",":","-.","-."];

function_processSampleECG_NoExp(root_path, experiments_names, result_names, dt_sim, pecg_name, results_folder_name, colors, lines);

%% LADx

root_path         = 'D:/Paper3/Simulations/invivo/mi/la/';
experiments_names = {'pig 8 HE','pig 8 MI', 'pig 9 HE','pig 9 MI', 'pig 10 HE','pig 10 MI', 'pig 11 HE','pig 11 MI', 'pig 12 HE','pig 12 MI'};
result_names      = {'sample8/results_he_CL1000_3000ms', ...
                    'sample8/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE', ...
                    'sample9/results_he_CL1000_3000ms', ...
                    'sample9/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE', ...
                    'sample10/results_he_CL1000_3000ms', ...
                    'sample10/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE', ...
                    'sample11/results_he_CL1000_3000ms', ...
                    'sample11/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE', ...
                    'sample12/results_he_CL1000_3000ms', ...
                    'sample12/results_mi_CL1000_3000ms_AVERAGE_noscar_BASE'};
dt_sim            = 0.00025; %s
pecg_name         = {'pECG_electrodesoriginal_norot',...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot', ...
                    'pECG_electrodesoriginal_norot'};
results_folder_name = 'ecg_results_electrodesoriginal_norot_miECG_LADx';

colorHE = [0 0.4470 0.7410];
colorMI = [0.8500 0.3250 0.0980];

colors = {colorHE, colorMI, colorHE, colorMI, colorHE, colorMI, colorHE, colorMI, colorHE, colorMI};

lines = ["-","-","--","--",":",":","-.","-.","-","-"];

function_processSampleECG_NoExp(root_path, experiments_names, result_names, dt_sim, pecg_name, results_folder_name, colors, lines);



