function [positionqrs]=wavedelianation_func(carpetabiosig,sigdir,ecgnr,signal, fs, flags, anot_fmt)
    % INPUT:
    % carpetabiosig=directory where Biosig is saved
    % sigdir=directory where Biosig saves temporarly the signalfor computation
    % ecg_nm_f=ecg to be delineated
    %OUTPUT:
    % positionqrs= ecg wave annotation
    
    % Folder BSB
    addpath([carpetabiosig, 'BioSigBrowser/Graphical_mode/BioSigBrowser/ver4'],...
        [carpetabiosig, 'BioSigBrowser/Graphical_mode/AnnotationFileManager/working'],...
        [carpetabiosig, 'BioSigBrowser/Gral_Functions/working'],...
        [carpetabiosig, 'tools/ecgtb_new/ver2'],...
        [carpetabiosig, 'tools/filtering/ver2'],...
        [carpetabiosig, 'tools/input_output/ver3'],...
        [carpetabiosig, 'tools/input_output/biosigt200'],...
        [carpetabiosig, 'tools/others/ver1'],...
        [carpetabiosig, 'WAVEDET/WAVEDET_DETECTION_TOOLS/ver2'],...
        [carpetabiosig, 'WAVEDET/WAVEDET_SINGLE_LEAD/ver1'],...
        [carpetabiosig, 'WAVEDET/WAVEDET_MULTI_LEAD/devel'],...
        [carpetabiosig, 'ISQUEMIA_BPC/ver1'],...
        [carpetabiosig, 'TWA/TWA_MULTILEAD/ver1'],...
        [carpetabiosig, 'VARIABILITY/VARIABILITY_TI_NP/ver1'],...
        [carpetabiosig, 'VARIABILITY/VARIABILITY_TI_P/ver1'],...
        [carpetabiosig, 'VARIABILITY/VARIABILITY_TV_NP/ver1'],...
        [carpetabiosig, 'VARIABILITY/VARIABILITY_NL/ver1'],...
        [carpetabiosig, 'VARIABILITY/VARIABILITY_NL/ver1/RQA'],...
        [carpetabiosig, 'EDR/ver1'],...
        [carpetabiosig, 'EDR/ver2'],...
        [carpetabiosig, 'QT_ADAPTATION/TI/ver1'],...
        [carpetabiosig, 'QT_ADAPTATION/TV/ver1'],...
        [carpetabiosig, 'QUALITY/ver1'],...
        [carpetabiosig, 'HRT/ver1'],...
        [carpetabiosig, 'APNEA_DETECTION/PPG_ARTIFACT_DETECTOR/ver1'],...
        [carpetabiosig, 'APNEA_DETECTION/PPG_PULSE_DETECTOR/LPDF/ver1'],...
        [carpetabiosig, 'APNEA_DETECTION/PPG_PULSE_DETECTOR/DER/ver1'],...
        [carpetabiosig, 'HBC/devel'],...
        [carpetabiosig, 'HBC/devel/common'],...
        [carpetabiosig, 'BRS/ver1']);
    
    % Detector QRS
    save(strcat(sigdir, ecgnr, '.mat'),'signal','fs','-mat');
    headir = sigdir;
    matdir = sigdir;
    t=[];
    lead=1; %size(signal_original,1);
    ft=2; %Formato .mat
    anot=[ecgnr '_wavannotqrs'];
    aname=append(ecgnr,'.qrs');
    dirann={sigdir};
    messages = [];
    [positionqrs,~,~] = wavedet_3D(sigdir,headir,matdir,ecgnr,ft,anot,lead,t,flags,anot_fmt,aname,dirann,messages);
    delete(strcat(sigdir,ecgnr,'.mat'));
    delete(strcat(sigdir,ecgnr,'.',anot));
end